### ISSUE TITLE
Use Case 1: Haematology

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-referral#1]
Portal to allow Haematology doctors to log current patients and discharge ex-patients

@GabPoll how do Haem currently provide this information?
Understanding this will help us think about how we could improve

**Comment by GabPoll** [comment]
Currently, haem docs produce an excel spreadsheet with demographics, haem team and underlying haem diagnosis.

Gill goes through lists and adds new patients to elCID. She copies and pastes the haem diagnosis as one long free text entry in the diagnosis field. Not sure if she assigns ward names and bed numbers. 

She adds these on micro-haem list view and so auto-tagged micro-haem.

Currently Gill does not remove patients on elCID who no longer appear on the list. However, she used to do this when T-card system was in operation - i.e. removed the T cards from the folder.

Question is more to the haematologists - how do they generate their excel spreadsheet - is it automatic? do they make it just for micro or does it have alternative uses for them? Important as a haem referral portal needs buy-in from them to have, at minimum, no net increase in their workload (preferably less). Would be helpful if once the system was up and running they were in position to only need to add new patients, but again depends on what they do at present.

**Comment by michaeledwardmarks** [comment]
So I think the referral portal would also allow you to fix the badness of the haematology diagnosis coding.
You could make the haematologists define:
- Underlying diagnosis
- BMT status (yes/no/type)
+/- Current chemo

**Comment by GabPoll** [comment]
yes, lots of potential there. In essence trying to get them to enter data for examples 1) & 3) https://github.com/openhealthcare/elcid/issues/124. This would massively change the data analysis for these patients, as these are really important variables - e.g. time of neutropaenia, time since transplant, etc...

**Comment by davidmiller** [comment]
I think this is now done ?

**Comment by GabPoll** [comment]
yes!
