### ISSUE TITLE
Feedback of referral to parent team

### ISSUE THREAD

**Issue by GabPoll** [openhealthcare/opal-referral#6]
This really is more of a concept idea for discussion.

If parent team refers a patient, that patient is entered onto a ward round, and a decision on patient's care is reached at the ward round, do we want that fed back directly to the parent team. Perhaps as a single email summarising all decisions made at that round on all the patients reviewed. 

Might help on governance issue to prevent misunderstanding / mis-documentation of advice being given per patient.

**Comment by michaeledwardmarks** [comment]
Good idea.
Note that email for elCID not currently working due to something at the ICT end.

**Comment by davidmiller** [comment]
This is a thing for openhealthcare/cedar

**Comment by GabPoll** [comment]
Ok, @davidmiller. Close here and see this: https://github.com/openhealthcare/cedar/issues/4
