### ISSUE TITLE
Reasons a referral portal is good

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-referral#7]
Important to consider.
For elCID at least this represents a change/extension of the current use-case.
Therefore saying why we want to do this important.

I think Information Governance is the win here.
Currently referrals rely on:
- Excel spreadsheets / Word Documents
- Person-to-person email 
- We hope but can't ensure that people use appropriate email addresses for these referrals

Bringing this within elCID moves everything clearly within the UCH firewall.
This is good.

**Comment by davidmiller** [comment]
Good to capture these - but I'm closing this as non-actionable ! :)
